chcp 65001 >nul
chcp 65001 >nul
@echo off
SETLOCAL ENABLEDELAYEDEXPANSION

SET "WORKSPACE=D:\review-system-new - codex"
SET "SCRIPTS_DIR=%WORKSPACE%\scripts"
SET "CF_EXE=%SCRIPTS_DIR%\cloudflared.exe"

IF NOT EXIST "%CF_EXE%" (
    ECHO [ERROR] cloudflared.exe not found at: %CF_EXE%
    ECHO Please download from: https://github.com/cloudflare/cloudflared/releases
    ECHO Place it in: %SCRIPTS_DIR%\
    PAUSE
    EXIT /B 1
)

ECHO.
ECHO ================================================
ECHO   Cloudflare Tunnel Setup Wizard
ECHO ================================================
ECHO.

REM --- Step 1: Authenticate ---
ECHO [Step 1/4] Authenticating cloudflared ...
ECHO.
ECHO Choose auth method:
ECHO   1) Browser OAuth (recommended)
ECHO   2) Manual Token
ECHO.
SET /P AUTH_METHOD="Enter option (1 or 2): "

IF "!AUTH_METHOD!"=="1" (
    ECHO.
    ECHO Opening browser for OAuth authentication...
    "%CF_EXE%" tunnel login
    IF !errorlevel! NEQ 0 (
        ECHO [ERROR] Authentication failed!
        PAUSE
        EXIT /B 1
    )
    ECHO [OK] Authenticated successfully.
) ELSE (
    ECHO.
    SET /P TOKEN_INPUT="Enter QUOTED_TUNNEL_TOKEN (with double quotes): "
    ECHO !TOKEN_INPUT! > "%SCRIPTS_DIR%\.tunnel-token.txt"
    ECHO [OK] Token saved.
)

REM --- Step 2: Create Tunnels ---
ECHO.
ECHO [Step 2/4] Creating Tunnels ...
ECHO.

ECHO --- Creating Frontend Tunnel ---
"%CF_EXE%" tunnel --no-autoupdate create review-frontend
IF !errorlevel! NEQ 0 (
    ECHO [ERROR] Failed to create frontend tunnel!
    PAUSE
    EXIT /B 1
)
SET /P FE_UUID="Enter Frontend Tunnel UUID: "

ECHO.
ECHO --- Creating PB Tunnel ---
"%CF_EXE%" tunnel --no-autoupdate create review-pb
IF !errorlevel! NEQ 0 (
    ECHO [ERROR] Failed to create PB tunnel!
    PAUSE
    EXIT /B 1
)
SET /P PB_UUID="Enter PB Tunnel UUID: "

REM Save UUIDs
ECHO !FE_UUID! > "%SCRIPTS_DIR%\frontend-uuid.txt"
ECHO !PB_UUID! > "%SCRIPTS_DIR%\pb-uuid.txt"

REM --- Step 3: Bind Domains ---
ECHO.
ECHO [Step 3/4] Binding Domains ...
ECHO.
ECHO Enter your Cloudflare registered domain (e.g. mysite.com):
SET /P MY_DOMAIN="Domain: "

ECHO.
ECHO Enter frontend subdomain (e.g. app or www):
SET /P FE_SUBDOMAIN="Frontend subdomain: "

ECHO.
ECHO Enter PB subdomain (e.g. api or pb):
SET /P PB_SUBDOMAIN="PB subdomain: "

ECHO.
ECHO --- Binding Frontend Domain ---
ECHO Will bind: https://!FE_SUBDOMAIN!.!MY_DOMAIN! -> Frontend (:5173)
"%CF_EXE%" tunnel --no-autoupdate route dns review-frontend !FE_SUBDOMAIN!.!MY_DOMAIN!
IF !errorlevel! NEQ 0 (
    ECHO [ERROR] Failed to bind frontend domain!
    PAUSE
    EXIT /B 1
)

ECHO.
ECHO --- Binding PB Domain ---
ECHO Will bind: https://!PB_SUBDOMAIN!.!MY_DOMAIN! -> PocketBase (:8091)
"%CF_EXE%" tunnel --no-autoupdate route dns review-pb !PB_SUBDOMAIN!.!MY_DOMAIN!
IF !errorlevel! NEQ 0 (
    ECHO [ERROR] Failed to bind PB domain!
    PAUSE
    EXIT /B 1
)

ECHO.
ECHO [OK] Domain binding successful!

REM --- Step 4: Generate .env.production ---
ECHO.
ECHO [Step 4/4] Generating .env.production ...
ECHO.

(
ECHO # Auto-generated by setup-tunnel.bat
ECHO # Do not edit manually. Re-run this script to update.
ECHO VITE_PB_URL=https://!PB_SUBDOMAIN!.!MY_DOMAIN!
) > "%WORKSPACE%\.env.production"

ECHO [OK] .env.production generated:
ECHO      VITE_PB_URL=https://!PB_SUBDOMAIN!.!MY_DOMAIN!
ECHO.

ECHO ================================================
ECHO   Setup Complete!
ECHO ================================================
ECHO.
ECHO Next steps:
ECHO   1. Run   npm run build
ECHO   2. Run   scripts\start-all.bat
ECHO   3. Visit https://!FE_SUBDOMAIN!.!MY_DOMAIN!
ECHO.
PAUSE